fixed worktree and example

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -120,7 +120,14 @@ jobs:
       - name: Build SDK
         run: make build_${{ matrix.language }}_sdk
       - name: Check worktree clean
-        run: ./ci-scripts/ci/check-worktree-is-clean
+        run: |
+          git update-index -q --refresh
+          if ! git diff-files --quiet; then
+              >&2 echo "error: working tree is not clean, aborting!"
+              git status
+              git diff
+              exit 1
+          fi
       - name: Compress SDK folder
         run: tar -zcf sdk/${{ matrix.language }}.tar.gz -C sdk/${{ matrix.language }}
           .
@@ -143,7 +150,6 @@ jobs:
           role-session-name: ${{ env.PROVIDER }}@githubActions
           role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
       - name: Run tests
-        # Tell make to not rebuild the provider bin
         run: make test_${{ matrix.language }}
     strategy:
       fail-fast: false
